export const paintingData = [
  // Front Wall
  {
    imgSrc: `artworks/1.jpg`,
    width: 6.7,
    height: 7.9,
    position: { x: -15, y: 2, z: -19.5 },
    rotationY: 0,
    info: {
      title: `Mice Nibbling at a Watermelon`,
      artist: 'Yi Am',
      description: `This painting depicts two mice eating a watermelon, with butterflies and flowers around, showcasing the delicate and detailed work of the artist.`,
      year: `16th century`,
      link: 'https://en.wikipedia.org/wiki/Yi_Am',
    },
  },
  {
    imgSrc: `artworks/2.jpg`,
    width: 6.1,
    height: 6.9,
    position: { x: -5, y: 2, z: -19.5 },
    rotationY: 0,
    info: {
      title: `Korean Genre Painting`,
      artist: 'Kim Hong-do (Danwon)',
      description: `This painting captures a scene of traditional Korean musicians and dancers, representing everyday life in Korea during the Joseon Dynasty.`,
      year: `18th century`,
      link: 'https://en.wikipedia.org/wiki/Kim_Hong-do',
    },
  },
  {
    imgSrc: `artworks/3.png`,
    width: 6.5,
    height: 8.1,
    position: { x: 5, y: 2, z: -19.5 },
    rotationY: 0,
    info: {
      title: `Portrait of a Woman`,
      artist: 'Ko Hui-dong',
      description: `This portrait by Ko Hui-dong, a pioneering Korean modern artist, reflects the influence of Western art styles on traditional Korean painting techniques.`,
      year: `1928`,
      link: 'https://en.wikipedia.org/wiki/Ko_Hui-dong',
    },
  },
  {
    imgSrc: `artworks/4.jpg`,
    width: 8.5,
    height: 5.6,
    position: { x: 15, y: 2, z: -19.5 },
    rotationY: 0,
    info: {
      title: `Bull`,
      artist: 'Lee Jung-seob',
      description: `Lee Jung-seob's painting of a bull is a powerful expression of resilience and strength, created during a turbulent period in Korean history.`,
      year: `1950s`,
      link: 'https://en.wikipedia.org/wiki/Lee_Jung-seob',
    },
  },
  // Back Wall
  {
    imgSrc: `artworks/5.jpg`,
    width: 6.5,
    height: 8.1,
    position: { x: -15, y: 2, z: 19.5 },
    rotationY: Math.PI,
    info: {
      title: `Self-Portrait`,
      artist: 'Chun Kyung-Ja',
      description: `This striking self-portrait by Chun Kyung-Ja features vivid colors and a surreal depiction of the artist, reflecting her unique style and emotional intensity.`,
      year: `1977`,
      link: 'https://en.wikipedia.org/wiki/Chun_Kyung-Ja',
    },
  },
  {
    imgSrc: `artworks/6.jpg`,
    width: 7.8,
    height: 11.5,
    position: { x: -5, y: 2, z: 19.5 },
    rotationY: Math.PI,
    info: {
      title: `Tiger`,
      artist: 'Kim Hong-do (Danwon)',
      description: `This painting by Kim Hong-do portrays a tiger with meticulous detail, capturing the power and grace of the animal, characteristic of Korean folk painting.`,
      year: `Late 18th century`,
      link: 'https://en.wikipedia.org/wiki/Kim_Hong-do',
    },
  },
  {
    imgSrc: `artworks/7.jpg`,
    width: 9.0,
    height: 4.5,
    position: { x: 5, y: 2, z: 19.5 },
    rotationY: Math.PI,
    info: {
      title: `Landscape of Mt. Geumgang`,
      artist: 'Jeong Seon (Gyeomjae)',
      description: `A classic landscape painting depicting the serene and majestic mountains of Korea with his signature brushwork.`,
      year: `1734`,
      link: 'https://en.wikipedia.org/wiki/Jeong_Seon',
    },
  },
  {
    imgSrc: `artworks/8.jpg`,
    width: 8.2,
    height: 5.9,
    position: { x: -19.5, y: 2, z: -15 },
    rotationY: Math.PI / 2,
    info: {
      title: `Two Cats`,
      artist: 'Yi Am',
      description: `This painting by Yi Am depicts two cats in a serene setting with flowers, showcasing the artist's delicate and detailed brushwork.`,
      year: `16th century`,
      link: 'https://en.wikipedia.org/wiki/Yi_Am',
    },
  },
  {
    imgSrc: `artworks/9.jpg`,
    width: 10.2,
    height: 5.9,
    position: { x: 15, y: 2, z: 19.5 },
    rotationY: Math.PI,
    info: {
      title: `Mountain and River`,
      artist: 'Gim Jeong-hui',
      description: `This painting by Gim Jeong-hui showcases a panoramic view of Korea's mountainous terrain and rivers, emphasizing traditional ink wash techniques.`,
      year: `1844`,
      link: 'https://en.wikipedia.org/wiki/Gim_Jeong-hui',
    },
  },
  {
    imgSrc: `artworks/10.jpg`,
    width: 5.5,  // Reduced size
    height: 5.5,  // Reduced size
    position: { x: -19.5, y: 2, z: -5 },
    rotationY: Math.PI / 2,
    info: {
      title: `Portrait of a Scholar`,
      artist: 'Yun Du-seo',
      description: `A detailed and expressive portrait of a scholar by Yun Du-seo, capturing the intellectual and dignified demeanor characteristic of Joseon portraiture.`,
      year: `1710`,
      link: 'https://en.wikipedia.org/wiki/Yun_Du-seo',
    },
  },
  {
    imgSrc: `artworks/11.jpg`,
    width: 9.5,
    height: 6.5,
    position: { x: -19.5, y: 2, z: 5 },
    rotationY: Math.PI / 2,
    info: {
      title: `Landscape of Mt. Geumgang`,
      artist: 'Jeong Seon (Gyeomjae)',
      description: `A beautiful landscape painting depicting the majestic Mt. Geumgang, demonstrating Jeong Seon's masterful brushwork and profound appreciation for nature.`,
      year: `1734`,
      link: 'https://en.wikipedia.org/wiki/Jeong_Seon',
    },
  },
  {
    imgSrc: `artworks/12.jpg`,
    width: 7.8,
    height: 10.0,
    position: { x: -19.5, y: 2, z: 15 },
    rotationY: Math.PI / 2,
    info: {
      title: `Peonies and Waterfalls`,
      artist: 'Unknown (Joseon Dynasty)',
      description: `This intricate painting features peonies and waterfalls, highlighting the beauty of nature through detailed and delicate brushwork.`,
      year: `18th century`,
      link: 'https://en.wikipedia.org/wiki/Joseon_art',
    },
  },
  // Right Wall
  {
    imgSrc: `artworks/13.jpg`,
    width: 6.5,
    height: 7.5,
    position: { x: 19.5, y: 2, z: -15 },
    rotationY: -Math.PI / 2,
    info: {
      title: `Couple under a Blossoming Tree`,
      artist: 'Unknown (Joseon Dynasty)',
      description: `This painting depicts a serene scene of a couple resting under a blossoming tree, illustrating the delicate beauty and intimate moments of traditional Korean life.`,
      year: `18th century`,
      link: 'https://en.wikipedia.org/wiki/Joseon_art',
    },
  },
  {
    imgSrc: `artworks/14.jpg`,
    width: 7.0,
    height: 6.0,
    position: { x: 19.5, y: 2, z: -5 },
    rotationY: -Math.PI / 2,
    info: {
      title: `Butterflies and Flowers`,
      artist: 'Shin Saimdang',
      year: `16th century`,
      link: 'https://en.wikipedia.org/wiki/Shin_Saimdang',
    },
  },
  {
  imgSrc: `artworks/15.jpg`,
  width: 10.0,
  height: 13.0,
  position: { x: 19.5, y: 2, z: 5 },
  rotationY: -Math.PI / 2,
  info: {
    title: `Buddhist Deities`,
    artist: 'Unknown (Joseon Dynasty)',
    description: `This elaborate painting features various Buddhist deities, showcasing the vibrant colors and intricate details typical of Joseon Buddhist art.`,
    year: `19th century`,
    link: 'https://en.wikipedia.org/wiki/Joseon_Buddhism',
  },
},
{
  imgSrc: `artworks/16.jpg`,
  width: 7.5,
  height: 10.0,
  position: { x: 19.5, y: 2, z: 15 },
  rotationY: -Math.PI / 2,
  info: {
    title: `Portrait of King Sejong`,
    artist: 'Unknown (Joseon Dynasty)',
    description: `A portrait of King Sejong the Great, one of Korea's most respected monarchs, who is known for creating the Korean alphabet, Hangul.`,
    year: `15th century`,
    link: 'https://en.wikipedia.org/wiki/Sejong_the_Great',
  },
},
{
  imgSrc: `artworks/17.jpg`,
  width: 8.0,
  height: 10.0,
  position: { x: 19.5, y: 2, z: 25 },
  rotationY: -Math.PI / 2,
  info: {
    title: `Tiger and Magpie`,
    artist: 'Unknown (Joseon Dynasty)',
    description: `This traditional Korean painting depicts a tiger and a magpie, symbolizing the juxtaposition of ferocity and innocence, a common theme in Korean folklore.`,
    year: `19th century`,
    link: 'https://en.wikipedia.org/wiki/Korean_art',
  },
},
];




